# Autogenerated wrapper script for Fparser_jll for aarch64-apple-darwin
export libfparser

JLLWrappers.@generate_wrapper_header("Fparser")
JLLWrappers.@declare_library_product(libfparser, "@rpath/libfparser.4.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libfparser,
        "lib/libfparser.4.5.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
