# Autogenerated wrapper script for Fparser_jll for powerpc64le-linux-gnu-cxx11
export libfparser

JLLWrappers.@generate_wrapper_header("Fparser")
JLLWrappers.@declare_library_product(libfparser, "libfparser.so.4")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libfparser,
        "lib/libfparser.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
