# Autogenerated wrapper script for Fparser_jll for x86_64-w64-mingw32-cxx11
export libfparser

JLLWrappers.@generate_wrapper_header("Fparser")
JLLWrappers.@declare_library_product(libfparser, "libfparser.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libfparser,
        "bin\\libfparser.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
